// GENERATED by scripts/legal-build.mjs — DO NOT EDIT. Run `npm run legal:build`.

export interface LegalDocContent {
  /** URL slug and record key, e.g. "terms". */
  slug: string;
  /** Short cross-nav label, e.g. "Terms". */
  navLabel: string;
  /** Document title (the source H1), e.g. "ESSENCE Terms of Service". */
  title: string;
  /** Human effective-date label, e.g. "September 1, 2026". */
  effectiveLabel: string;
  /** Pre-rendered, leak-checked body HTML (from the reviewed markdown). */
  html: string;
}

/** Ordered slugs — drives cross-document footer nav. */
export const LEGAL_ORDER = ["terms", "privacy", "acceptable-use", "beta-terms"] as const;

export const LEGAL_DOCS: Record<string, LegalDocContent> = {
  "terms": {
    slug: "terms",
    navLabel: "Terms",
    title: "ESSENCE Terms of Service",
    effectiveLabel: "September 1, 2026",
    html: `<h2>1. Who we are</h2>
<p>ESSENCE is operated by <strong>ESSENCE APP LLC</strong>, a Florida limited liability company (&quot;ESSENCE,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). Our principal address is 610 W Las Olas Blvd, #513, Fort Lauderdale, FL 33312. You can reach us at <strong><a href="mailto:help@essencevault.app">help@essencevault.app</a></strong>.</p>
<p>These Terms of Service (&quot;Terms&quot;) are a binding agreement between you and ESSENCE APP LLC governing your use of the ESSENCE website at essencevault.app and the ESSENCE application (together, the &quot;Service&quot;).</p>
<p>By creating an account or using the Service, you agree to these Terms, to our <a href="/privacy">Privacy Policy</a>, and to our <a href="/acceptable-use">Acceptable Use Policy</a>. If you do not agree, do not use the Service.</p>
<h2>2. What ESSENCE is, and what it is not</h2>
<p><strong>What the Service does today.</strong> ESSENCE lets you record your own voice by reading a series of scripted prompts aloud. We send those recordings to a third-party voice provider, which creates a synthetic model of your voice. You can then create messages inside your account. Each message is generated from a fixed template plus a short personalized note you write, and is rendered as audio in your synthetic voice. You can play back your saved messages inside your account at any time.</p>
<p><strong>What the Service does not do.</strong> Please read this section carefully, because it is the most important thing to understand about ESSENCE today:</p>
<ul>
<li><strong>We do not deliver messages to anyone.</strong> There is no email, text message, mail, or other delivery of your messages to any other person, at any time, under any circumstance.</li>
<li><strong>No one else can listen to your messages.</strong> Messages are played back only by you, from inside your own authenticated account.</li>
<li><strong>&quot;Recipients&quot; are private labels, not delivery targets.</strong> When you tag a message with a person&#39;s name and relationship, that label is stored privately in your own account. We do not collect that person&#39;s email address, phone number, or any other contact information, and we never contact them.</li>
<li><strong>There is no scheduled or posthumous release.</strong> ESSENCE has no scheduling feature, no death or incapacity verification, no dead man&#39;s switch, no trusted contact, and no release trigger of any kind. Nothing in your account is released to anyone upon your death or at any future date.</li>
</ul>
<p>If we ever build a delivery feature, we will describe it in updated Terms before it is turned on. <strong>Do not use ESSENCE on the assumption that your messages will reach anyone. They will not.</strong> ESSENCE is, today, a private voice keepsake vault for your own use.</p>
<h2>3. ESSENCE is not a will, trust, or estate service</h2>
<p>ESSENCE is <strong>not</strong> a will, a trust, an estate-planning service, a digital estate custodian, an executor, a trustee, a fiduciary, a probate tool, or a legal or financial advisor. Nothing you create in ESSENCE has legal effect as a testamentary document, a bequest, a power of attorney, an advance directive, or any other legally operative instruction.</p>
<p><strong>Do not use ESSENCE as the only place you store legally or practically important information.</strong> That includes wills and codicils, asset inventories, account numbers, passwords, cryptocurrency seed phrases or private keys, funeral or burial instructions, medical or end-of-life directives, guardianship wishes, and insurance details. Keep that information with an attorney, a fiduciary, or another system built to preserve and act on it. ESSENCE will not surface, transmit, act on, or honor any such instruction, and we are not responsible if information stored only in ESSENCE is never seen or acted upon.</p>
<h2>4. Eligibility and your account</h2>
<p>You must be <strong>at least 18 years old</strong> to use ESSENCE. The Service is not directed to children, and we do not knowingly create voice models from the voices of minors.</p>
<p>You are responsible for the security of your account and for everything that happens under it. We sign you in with a one-time email link, so keeping control of your email account is what keeps your ESSENCE account secure. Tell us at <a href="mailto:help@essencevault.app">help@essencevault.app</a> if you believe someone else has accessed your account.</p>
<p>You may hold one account. You may not share your account, sell it, or transfer it to another person.</p>
<h2>5. Your voice and your recordings</h2>
<h3>5.1 You own your content</h3>
<p>You own your voice recordings, the messages you create, and the personalized notes you write (&quot;Your Content&quot;). We do not claim ownership of any of it.</p>
<h3>5.2 The permission you give us</h3>
<p>To operate the Service for you, you grant ESSENCE a limited, worldwide, non-exclusive, royalty-free license to host, store, copy, transmit, process, and display Your Content, and to transmit your recordings to the service providers listed in our Privacy Policy, <strong>solely in order to provide the Service to you.</strong> This license exists only so the software can work. It ends when you delete the content or your account, except for copies retained in routine backups for the limited windows described in our Privacy Policy.</p>
<p><strong>We will not</strong> sell Your Content, license it to third parties for their own purposes, use your voice in marketing, or use Your Content to train artificial intelligence models. See the Privacy Policy for how we have configured our voice provider to support this.</p>
<h3>5.3 Consent to create a synthetic voice</h3>
<p>Creating a synthetic voice is optional, and it does not happen unless you affirmatively consent to it in the app. Before we create your voice model, you must confirm:</p>
<blockquote>
<p><strong>I consent to ESSENCE and its service providers creating and operating a synthetic model of my voice from these recordings, and generating audio in that voice for me.</strong></p>
</blockquote>
<p>You may withdraw that consent at any time by deleting your account, which instructs our voice provider to delete the voice model. Withdrawing consent does not undo processing that already took place.</p>
<h3>5.4 It must be your own voice</h3>
<p><strong>You may only create a voice model from your own voice.</strong> Before recording, you must confirm:</p>
<blockquote>
<p><strong>This is my own voice. I am not recording, imitating, or submitting the voice of any other person, living or deceased.</strong></p>
</blockquote>
<p>We do not currently support creating a voice model from another person&#39;s voice, including a family member&#39;s, even with their permission and even for preservation reasons. We know that is a real and sincere thing people want. We are not equipped to verify that kind of consent yet, so we do not allow it. If we build a supported path for it, we will publish the process and the consent requirements before enabling it.</p>
<p>You are solely responsible for the audio you record. We do not perform speaker verification, liveness detection, or biometric matching, which means our systems will accept any audio your microphone hears. That technical fact does not grant you permission. Submitting another person&#39;s voice is a breach of these Terms and of our Acceptable Use Policy, and may violate biometric privacy laws, right-of-publicity laws, and criminal impersonation and fraud laws where you live.</p>
<h3>5.5 Third-party material</h3>
<p>Do not record copyrighted material you do not have rights to, including song lyrics, published works, speeches, and audiobook or film dialogue. Read the prompts in your own words. We do not screen recordings for copyright, so this obligation is yours.</p>
<h2>6. AI-generated content</h2>
<p>Messages in ESSENCE are generated by artificial intelligence. Two things follow from that:</p>
<ul>
<li><strong>The audio is synthetic.</strong> It is a machine-generated approximation of your voice, not a recording of you saying those words. It may contain errors in pronunciation, emphasis, or tone.</li>
<li><strong>The words are partly generated.</strong> Your personalized note is rewritten by an AI model into a short passage, and is not spoken back verbatim. The rest of the message is fixed template text. Generated output may not reflect your exact intent. Review a message before saving it.</li>
</ul>
<p>We make no representation that generated audio is indistinguishable from your real voice, suitable for any particular purpose, or acceptable as proof of identity, consent, or intent. <strong>Never use ESSENCE audio for voice authentication, identity verification, or any other security or legal purpose.</strong></p>
<p>Messages are immutable once generated. You can discard a message in progress, but a saved message cannot be edited.</p>
<h2>7. Acceptable use</h2>
<p>Your use of ESSENCE is subject to our <a href="/acceptable-use">Acceptable Use Policy</a>, which is incorporated into these Terms. In short: no impersonation, no threats or harassment, no fraud, no illegal content, and no using another person&#39;s voice.</p>
<h2>8. Content removal, suspension, and termination</h2>
<p>We reserve the right, but do not assume any obligation, to remove content, restrict features, and suspend or terminate an account, with or without notice, where we reasonably believe it is necessary to comply with law, respond to a legal demand, address a violation of these Terms or the Acceptable Use Policy, protect the safety of any person, or protect the Service.</p>
<p>We do not review or monitor content proactively, and we have no general obligation to do so. Content review, where it occurs, is manual and complaint-driven. To report a violation, email <strong><a href="mailto:help@essencevault.app">help@essencevault.app</a></strong> with the details.</p>
<p>You may stop using ESSENCE at any time and may delete your account from Settings. Deletion is immediate and permanent. There is no recovery period, no undo, and no export. What deletion does and does not remove is described in the Privacy Policy, and you should read that section before you delete anything.</p>
<h2>9. Subscriptions, trial, and billing</h2>
<h3>9.1 Plans and price</h3>
<p>ESSENCE offers a single paid subscription, <strong>Voice Vault</strong>, billed at <strong>US$12.99 per month</strong> or <strong>US$119.00 per year</strong>. Prices are in US dollars and exclude any taxes that may apply. We may change prices on notice; a price change applies to your next renewal, never to a term you have already paid for.</p>
<h3>9.2 Free trial</h3>
<p>New subscribers may be offered a <strong>7-day free trial</strong>. The trial is available once per customer, on your first subscription only. <strong>You must provide a payment method to start the trial, and unless you cancel before the trial ends, the subscription begins automatically and your payment method is charged.</strong></p>
<h3>9.3 Automatic renewal</h3>
<p><strong>Your subscription renews automatically</strong> at the end of each billing period, monthly or annual as selected, and your payment method is charged the then-current price, <strong>until you cancel.</strong> You consent to this recurring charge when you subscribe.</p>
<h3>9.4 Cancelling</h3>
<p>You may cancel at any time from the billing portal linked in your account settings. <strong>Cancellation takes effect at the end of your current paid period, not immediately.</strong> You keep full access until that date, and you are not charged again.</p>
<h3>9.5 Refunds</h3>
<p>If you are unhappy with ESSENCE, email <strong><a href="mailto:help@essencevault.app">help@essencevault.app</a></strong> within <strong>14 days of your first paid charge</strong> and we will refund that charge in full. Beyond that window, payments and renewal charges are non-refundable except where a refund is required by the law that applies to you. Refunds are issued to the original payment method.</p>
<p>To avoid a renewal charge you do not want, cancel before the renewal date. We do not provide partial refunds for unused time in a period you have already started.</p>
<h3>9.6 What happens if your subscription ends</h3>
<p>Today, if your subscription lapses or is cancelled:</p>
<ul>
<li><strong>You keep access to messages you have already saved and can continue playing them back.</strong></li>
<li><strong>You cannot create or save new messages.</strong></li>
<li>We do not delete your content because of non-payment.</li>
</ul>
<p>We reserve the right to change this in the future, including restricting playback or removing content after a prolonged period of non-payment. <strong>If we do, we will give you at least 30 days&#39; notice by email before any content is removed</strong>, and an opportunity to resubscribe.</p>
<h3>9.7 Payment processing</h3>
<p>Payments are processed by <strong>Stripe</strong>. We do not receive or store your full card number. Your use of the payment flow is also subject to Stripe&#39;s terms. If a payment fails, we retry it according to Stripe&#39;s standard schedule; if it continues to fail, your subscription lapses as described above.</p>
<h3>9.8 Limits</h3>
<p>The Service has usage limits, which are displayed in the app and may change. As of the current version these include a cap on the number of saved messages, one voice profile per account, and rate limits on recording and generation. Limits exist to control cost and abuse. Exceeding a limit blocks new activity; it never deletes existing content.</p>
<h2>10. Service availability and changes</h2>
<p>ESSENCE depends on third-party infrastructure, including Supabase, Vercel, Stripe, ElevenLabs, and Anthropic. <strong>We do not guarantee that the Service will be available, uninterrupted, error-free, or preserved indefinitely.</strong> We may modify, suspend, or discontinue any part of the Service, and we may discontinue the Service entirely.</p>
<p><strong>If we discontinue the Service, we will make reasonable efforts to give you at least 30 days&#39; notice by email so that you can retrieve your content.</strong></p>
<p><strong>ESSENCE is not an archive, a backup service, or a permanent preservation service, and we make no durability guarantee.</strong> If your recordings and messages matter to you, keep your own copies elsewhere.</p>
<h2>11. Disclaimers</h2>
<p><strong>THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE,&quot; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED.</strong> To the fullest extent permitted by law, we disclaim all implied warranties, including merchantability, fitness for a particular purpose, title, and non-infringement.</p>
<p>Without limiting the above, <strong>we specifically disclaim any liability for</strong>:</p>
<ul>
<li><strong>Failed, delayed, or non-existent delivery</strong> of any message to any person. The Service does not deliver messages. We are not liable for any consequence of a message not reaching anyone.</li>
<li><strong>Incorrect, outdated, or mistaken recipient labels.</strong> Recipient names are free text that you enter, and we do not verify them.</li>
<li><strong>The conduct or reactions of any person</strong> who at any time hears, obtains, or reacts to content created in ESSENCE.</li>
<li><strong>Third-party service outages, failures, changes, price changes, or data loss</strong> at any provider we depend on.</li>
<li><strong>Loss, corruption, or non-preservation of content</strong>, however caused. We make no guarantee of permanent preservation.</li>
<li><strong>Emotional distress, grief, or psychological harm</strong> arising from the creation, playback, absence, loss, or content of any message, including messages that reference death, loss, or a person who has died.</li>
<li><strong>Any reliance on ESSENCE for estate, legal, financial, medical, or end-of-life purposes</strong>, as described in Section 3.</li>
<li><strong>Any use of generated audio for authentication, identity verification, or evidentiary purposes.</strong></li>
</ul>
<p>ESSENCE is not a mental health, grief counseling, or crisis service. If you are in distress, please contact a qualified professional or a local crisis line.</p>
<h2>12. Limitation of liability</h2>
<p>To the fullest extent permitted by law, ESSENCE APP LLC and its members, officers, employees, and agents will not be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages, or for lost profits, lost data, lost content, loss of goodwill, or emotional distress, arising out of or relating to the Service, whether based in contract, tort, strict liability, or any other theory, and whether or not we were advised of the possibility of such damages.</p>
<p><strong>Our total aggregate liability to you for all claims arising out of or relating to the Service will not exceed the greater of (a) the total amount you paid us in the twelve months before the event giving rise to the claim, or (b) US$100.</strong></p>
<p>Some jurisdictions do not allow the exclusion or limitation of certain damages, so parts of Sections 11 and 12 may not apply to you. In that case our liability is limited to the greatest extent permitted by the law that applies to you.</p>
<h2>13. Indemnification</h2>
<p>You agree to indemnify and hold harmless ESSENCE APP LLC from any claim, demand, loss, or expense, including reasonable attorneys&#39; fees, arising out of your content, your use of the Service, your violation of these Terms or the Acceptable Use Policy, or your violation of the rights of any other person, including any claim that you created a voice model from a voice that was not your own.</p>
<h2>14. Governing law and venue</h2>
<p>These Terms are governed by the laws of the <strong>State of Florida</strong>, without regard to its conflict-of-laws rules.</p>
<p>You and ESSENCE agree that any dispute arising out of or relating to these Terms or the Service will be brought exclusively in the state courts located in <strong>Broward County, Florida</strong>, or in the <strong>United States District Court for the Southern District of Florida</strong>, and each party consents to the personal jurisdiction and venue of those courts.</p>
<p><strong>There is no mandatory arbitration clause and no class action waiver in these Terms.</strong></p>
<p>If you use the Service from outside the United States, you do so on your own initiative and are responsible for compliance with local law. Nothing in this section removes any right you have under mandatory consumer protection law in your country of residence to bring a claim in your local courts or under your local law.</p>
<h2>15. Changes to these Terms</h2>
<p>We may update these Terms. If a change is material, we will notify you by email or in the app at least <strong>14 days</strong> before it takes effect. Continuing to use the Service after a change takes effect means you accept the updated Terms. If you do not accept, stop using the Service and delete your account. We will keep prior versions available on request at <a href="mailto:help@essencevault.app">help@essencevault.app</a>.</p>
<h2>16. General</h2>
<p><strong>Entire agreement.</strong> These Terms, the Privacy Policy, and the Acceptable Use Policy are the entire agreement between you and ESSENCE regarding the Service.</p>
<p><strong>Severability.</strong> If any provision is unenforceable, the rest remains in effect.</p>
<p><strong>No waiver.</strong> Our failure to enforce a provision is not a waiver of it.</p>
<p><strong>Assignment.</strong> You may not assign these Terms. We may assign them to a successor in connection with a merger, acquisition, or sale of assets, on notice to you.</p>
<p><strong>Force majeure.</strong> We are not liable for failures caused by events beyond our reasonable control.</p>
<h2>17. Contact</h2>
<p><strong>ESSENCE APP LLC</strong>
610 W Las Olas Blvd, #513, Fort Lauderdale, FL 33312
<a href="mailto:help@essencevault.app">help@essencevault.app</a></p>`,
  },
  "privacy": {
    slug: "privacy",
    navLabel: "Privacy",
    title: "ESSENCE Privacy Policy",
    effectiveLabel: "September 1, 2026",
    html: `<h2>The short version</h2>
<ul>
<li>Your voice recordings are the most sensitive thing here, and we treat them that way.</li>
<li><strong>We do not sell your data, and we do not use your recordings to train AI models.</strong> We have turned off model training at our voice provider.</li>
<li><strong>We do not send your messages to anyone.</strong> There is no delivery feature. Only you can play back your messages.</li>
<li><strong>We do not use third-party analytics, advertising, or tracking.</strong> No Google Analytics, no pixels, no ad networks.</li>
<li>Deleting your account deletes your content from our systems right away and instructs our voice provider to delete your voice model.</li>
<li>This summary is for orientation. The sections below are what actually governs.</li>
</ul>
<hr>
<h2>1. Who is responsible for your data</h2>
<p><strong>ESSENCE APP LLC</strong>, a Florida limited liability company, 610 W Las Olas Blvd, #513, Fort Lauderdale, FL 33312, is the controller of the personal data described here.</p>
<p>Privacy and data-rights contact: <strong><a href="mailto:help@essencevault.app">help@essencevault.app</a></strong>. Please put &quot;Privacy request&quot; in the subject line.</p>
<h2>2. What we collect</h2>
<h3>2.1 Information you give us</h3>
<table>
<thead>
<tr>
<th>Category</th>
<th>What it is</th>
<th>Why we have it</th>
</tr>
</thead>
<tbody><tr>
<td><strong>Account</strong></td>
<td>Your email address</td>
<td>To create your account and sign you in by emailed link</td>
</tr>
<tr>
<td><strong>Profile</strong></td>
<td>First name, relationship label, city, birth year, home state, optional profile photo</td>
<td>To personalize the messages the Service generates for you</td>
</tr>
<tr>
<td><strong>Voice recordings</strong></td>
<td>Audio of you reading scripted prompts aloud, captured by your device microphone</td>
<td>To create and operate your synthetic voice</td>
</tr>
<tr>
<td><strong>Message content</strong></td>
<td>The message type you choose, the person label you attach, and the short personal note you write</td>
<td>To generate your message</td>
</tr>
<tr>
<td><strong>Person labels (&quot;recipients&quot;)</strong></td>
<td>A name, an optional relationship, and an optional private note</td>
<td>A private label inside your own vault. <strong>We collect no contact information for these people, and we never contact them</strong></td>
</tr>
<tr>
<td><strong>Support messages</strong></td>
<td>What you send to <a href="mailto:help@essencevault.app">help@essencevault.app</a></td>
<td>To answer you</td>
</tr>
</tbody></table>
<h3>2.2 Information created by using the Service</h3>
<table>
<thead>
<tr>
<th>Category</th>
<th>What it is</th>
</tr>
</thead>
<tbody><tr>
<td><strong>Synthetic voice model</strong></td>
<td>A voice model created by our provider from your recordings, and an identifier for it</td>
</tr>
<tr>
<td><strong>Generated message audio</strong></td>
<td>The MP3 files the Service produces in your voice</td>
</tr>
<tr>
<td><strong>Usage events</strong></td>
<td>First-party product analytics: which screens and actions occurred, timestamps, a session identifier, and your account id (so we can understand product usage per account). <strong>No audio and no message content are ever included in these events</strong></td>
</tr>
<tr>
<td><strong>Technical logs</strong></td>
<td>Server logs of requests and errors, containing identifiers and byte sizes. <strong>Our logger is configured not to log audio or message content</strong></td>
</tr>
<tr>
<td><strong>Subscription status</strong></td>
<td>Your plan, trial, renewal, and payment status, received from Stripe</td>
</tr>
</tbody></table>
<h3>2.3 What we do not collect</h3>
<p>We do not collect contact information for the people you name in your vault. We do not use advertising identifiers. We do not buy data about you from data brokers. We do not have a Google Analytics, Meta Pixel, TikTok Pixel, PostHog, Mixpanel, Hotjar, Segment, or session-replay integration. <strong>No analytics or tracking of any kind runs before you sign in.</strong></p>
<h2>3. Your voice is sensitive data, and here is how we handle it</h2>
<p>Voice recordings and the synthetic voice model created from them may be treated as <strong>biometric data</strong> or <strong>special category data</strong> under laws including the EU and UK GDPR and US state biometric privacy laws.</p>
<ul>
<li><strong>We process them only with your explicit consent.</strong> Before any synthetic voice is created, you must affirmatively consent in the app. If you do not consent, no voice model is created.</li>
<li><strong>You must confirm the voice is your own.</strong> We do not permit creating a voice model from another person&#39;s voice.</li>
<li><strong>You can withdraw consent</strong> at any time by deleting your account, which deletes your recordings from our systems and instructs our voice provider to delete the voice model. Withdrawal does not undo processing that already occurred.</li>
<li><strong>We do not use voice data for profiling, advertising, identity verification, or any purpose other than operating the Service for you.</strong></li>
</ul>
<p>Our legal bases, where the GDPR or UK GDPR applies: <strong>explicit consent</strong> (Article 9(2)(a)) for voice and biometric data; <strong>performance of a contract</strong> (Article 6(1)(b)) for account, message, and subscription data; <strong>legitimate interests</strong> (Article 6(1)(f)) for security, abuse prevention, and first-party product analytics; and <strong>legal obligation</strong> (Article 6(1)(c)) for tax and financial records.</p>
<h2>4. How we use your information</h2>
<p>We use your information to create your account and sign you in, create and operate your synthetic voice, generate and store your messages, let you play them back, take payment and manage your subscription, respond to your support requests, keep the Service secure and prevent abuse, understand which parts of the product are used so we can improve them, and comply with law.</p>
<p><strong>We do not</strong> sell your personal information, share it for cross-context behavioral advertising, use your recordings or messages to train artificial intelligence models, use your voice in marketing, or disclose your content to anyone except the service providers listed below and where legally required.</p>
<h2>5. Who processes your data on our behalf</h2>
<p>These are our service providers. Each processes data only to provide its service to us.</p>
<table>
<thead>
<tr>
<th>Provider</th>
<th>What it handles</th>
<th>Where</th>
</tr>
</thead>
<tbody><tr>
<td><strong>Supabase</strong></td>
<td>Database, authentication, and file storage for recordings, message audio, and photos</td>
<td>United States</td>
</tr>
<tr>
<td><strong>ElevenLabs</strong></td>
<td>Voice model creation and text-to-speech generation. Receives your voice recordings</td>
<td>United States</td>
</tr>
<tr>
<td><strong>Anthropic</strong></td>
<td>Rewrites your short personal note into the passage that appears in your message. Receives that note text only, never audio</td>
<td>United States</td>
</tr>
<tr>
<td><strong>Stripe</strong></td>
<td>Subscription payments. Receives your email and payment details directly. <strong>We never see or store your full card number</strong></td>
<td>United States</td>
</tr>
<tr>
<td><strong>Vercel</strong></td>
<td>Application hosting</td>
<td>United States</td>
</tr>
<tr>
<td><strong>Cloudflare</strong></td>
<td>Email routing for our support inbox</td>
<td>United States</td>
</tr>
</tbody></table>
<p>We may add or change providers. When we do, we will update this list, and we will give notice of a material change as described in Section 12.</p>
<h3>5.1 About our voice provider specifically</h3>
<p>Because it is the provider that touches your recordings, we want to be precise:</p>
<ul>
<li><strong>We have opted out of model training at ElevenLabs.</strong> As of 2026-07-12, before the Service was available to any user, the &quot;improve the models&quot; setting on our account is turned off. Your recordings are not used to train ElevenLabs&#39; models.</li>
<li><strong>When you delete your account, we call ElevenLabs to delete your voice model.</strong></li>
<li><strong>We cannot promise a vendor-side deletion deadline.</strong> ElevenLabs&#39; published policy caps retention at no longer than three years after the last interaction, and it does not publish a backup-purge timeline. We tell you exactly this rather than promising an immediate purge we cannot verify.</li>
<li>ElevenLabs acts as our processor under its published Data Processing Addendum.</li>
</ul>
<h2>6. Security, stated accurately</h2>
<ul>
<li><strong>In transit:</strong> all connections to the Service and to our providers use HTTPS/TLS.</li>
<li><strong>At rest:</strong> files and database records are stored on infrastructure that encrypts data at rest at the disk level, and the storage holding your recordings and photos is configured to be private rather than publicly readable. </li>
<li><strong>Access control:</strong> your account data is scoped to you. Application code checks ownership before it will produce a playback link, and playback links are short-lived and expire.</li>
</ul>
<p><strong>We want to be clear about what this is not.</strong> ESSENCE does <strong>not</strong> use end-to-end or client-side encryption. Our servers process your recordings in unencrypted form in order to send them to the voice provider and to generate your messages, which means our systems are technically capable of accessing your recordings. <strong>ESSENCE personnel do not access your recordings in the ordinary course of business.</strong> We access content only where necessary to operate or repair the Service, investigate a reported violation, or comply with a legal obligation.</p>
<p>No system is perfectly secure, and we cannot guarantee absolute security.</p>
<h2>7. How long we keep things, and what deletion actually does</h2>
<h3>7.1 While your account is open</h3>
<p>We keep your content for as long as your account exists, so the Service can work.</p>
<h3>7.2 When you delete your account</h3>
<p>Deleting your account from Settings is <strong>immediate and permanent</strong>. There is no grace period, no recovery window, and no undo. When you delete:</p>
<table>
<thead>
<tr>
<th>Data</th>
<th>What happens</th>
</tr>
</thead>
<tbody><tr>
<td>Voice recordings</td>
<td>Deleted from our storage immediately</td>
</tr>
<tr>
<td>Generated message audio</td>
<td>Deleted from our storage immediately</td>
</tr>
<tr>
<td>Profile and home photos</td>
<td>Deleted from our storage immediately</td>
</tr>
<tr>
<td>Messages, notes, person labels, profile</td>
<td>Deleted from our database immediately</td>
</tr>
<tr>
<td>Usage events</td>
<td>Deleted immediately</td>
</tr>
<tr>
<td>Your synthetic voice model at ElevenLabs</td>
<td>We send a delete instruction immediately. Their retention policy governs after that, as described in Section 5.1</td>
</tr>
<tr>
<td>Your subscription</td>
<td>Cancelled</td>
</tr>
<tr>
<td><strong>Payment records at Stripe</strong></td>
<td><strong>Retained.</strong> Invoices, charges, and customer records are kept by Stripe as required for tax, accounting, and anti-fraud purposes, and outlive your ESSENCE account</td>
</tr>
<tr>
<td><strong>Database backups</strong></td>
<td><strong>Deleted records persist in routine database backups for up to 7 days</strong> and then age out. Backups are not selectively edited</td>
</tr>
</tbody></table>
<p><strong>Please read that last row.</strong> We do not claim that your data is gone from every system the instant you press delete. Your files are removed immediately, and database records age out of backups within about a week.</p>
<h3>7.3 If you stop paying</h3>
<p>We do not delete your content because a subscription lapsed. See the Terms of Service for what access you keep.</p>
<h2>8. Your rights and how to use them</h2>
<p>Depending on where you live, you may have the right to access your data, receive a copy in a portable format, correct it, delete it, object to or restrict certain processing, withdraw consent, and not be discriminated against for exercising these rights.</p>
<p><strong>How to exercise them:</strong> email <strong><a href="mailto:help@essencevault.app">help@essencevault.app</a></strong> with &quot;Privacy request&quot; in the subject line, from the email address on your account.</p>
<p><strong>Be aware of how this works today, because we would rather tell you than have you discover it.</strong> ESSENCE does not yet have self-serve data export or a way to delete an individual recording or message. <strong>We handle these requests manually.</strong> We will acknowledge your request within <strong>7 days</strong> and complete it within <strong>30 days</strong>, or tell you why we need longer, up to the extension your law allows. Full account deletion is the one right you can exercise yourself, instantly, from Settings.</p>
<p>We do not charge for these requests. We may need to verify that the request comes from you, which we do by confirming control of the account email.</p>
<p>If you are in the EEA, the UK, or Switzerland, you also have the right to lodge a complaint with your local data protection authority.</p>
<p>If you are a California resident: we do not sell or share your personal information as those terms are defined under the CCPA/CPRA, and we do not use or disclose sensitive personal information beyond the purposes permitted for providing the Service.</p>
<h2>9. Cookies and similar technologies</h2>
<p>We use <strong>strictly necessary cookies only</strong>, to keep you signed in. We do not use advertising, marketing, or analytics cookies. Our product analytics use a random session identifier stored in your browser&#39;s session storage, which is cleared when you close the tab, is not a cookie, and is created only after you sign in.</p>
<h2>10. International data transfers</h2>
<p>The Service is operated from the United States, and your data is processed there. If you use ESSENCE from the EEA, the UK, or another country with data transfer restrictions, your data is transferred to the United States. Our providers rely on Standard Contractual Clauses, and in some cases the EU-US Data Privacy Framework, to cover those transfers. You can request more detail at <a href="mailto:help@essencevault.app">help@essencevault.app</a>.</p>
<h2>11. Children</h2>
<p>ESSENCE is for adults. You must be 18 or older. We do not knowingly collect personal data from anyone under 18 or create a voice model from a minor&#39;s voice. If you believe a minor has used the Service, email <a href="mailto:help@essencevault.app">help@essencevault.app</a> and we will delete the account.</p>
<h2>12. Changes to this policy</h2>
<p>If we make a material change, we will notify you by email or in the app at least <strong>14 days</strong> before it takes effect. <strong>If a change would materially expand how we use your voice data, we will ask for your consent again rather than relying on notice.</strong></p>
<h2>13. Contact</h2>
<p><strong>ESSENCE APP LLC</strong>
610 W Las Olas Blvd, #513, Fort Lauderdale, FL 33312
<a href="mailto:help@essencevault.app">help@essencevault.app</a></p>`,
  },
  "acceptable-use": {
    slug: "acceptable-use",
    navLabel: "Acceptable Use",
    title: "ESSENCE Acceptable Use Policy",
    effectiveLabel: "September 1, 2026",
    html: `<h2>Why this exists</h2>
<p>ESSENCE creates a synthetic model of your voice. A convincing voice is a powerful thing, and it can be used to hurt people. This policy sets the line. It is short on purpose, so there is no confusion about what is not allowed.</p>
<h2>1. The voice must be yours</h2>
<p><strong>You may only create a voice model from your own voice.</strong></p>
<p>You may not:</p>
<ul>
<li>Record, imitate, or submit the voice of any other person, living or deceased, including a family member, a public figure, a celebrity, or a fictional or synthetic voice belonging to someone else.</li>
<li>Play a recording of another person&#39;s voice into your microphone, or submit audio captured from a call, a video, a broadcast, a podcast, or any other source.</li>
<li>Attempt to defeat, work around, or test our controls in order to clone a voice that is not yours.</li>
</ul>
<p>Our systems do not perform speaker verification, so they will accept audio you are not permitted to submit. <strong>The absence of a technical block is not permission.</strong> Doing this may violate biometric privacy laws, right-of-publicity laws, and criminal impersonation and fraud statutes, and you are solely responsible if it does.</p>
<h2>2. No impersonation or deception</h2>
<p>You may not use ESSENCE, or any audio created with it, to:</p>
<ul>
<li>Impersonate any person or organization, or misrepresent who is speaking.</li>
<li>Create audio intended to be mistaken for a genuine recording of a real event, statement, or conversation.</li>
<li>Deceive a person, a business, a financial institution, or a government body.</li>
<li>Defeat or attempt to defeat any voice authentication, identity verification, or biometric security system. <strong>This includes your own.</strong> ESSENCE audio is not an identity credential and must never be used as one.</li>
</ul>
<h2>3. No harm to others</h2>
<p>You may not create, store, or share content that:</p>
<ul>
<li>Threatens, harasses, stalks, intimidates, bullies, or targets a person for abuse.</li>
<li>Incites, promotes, or provides instructions for violence, self-harm, or illegal activity.</li>
<li>Attacks or degrades a person or group based on a protected characteristic.</li>
<li>Is sexually explicit, sexualizes a minor in any way, or constitutes non-consensual intimate content.</li>
<li>Defames a person, or discloses another person&#39;s private information without their consent.</li>
<li>Constitutes fraud, extortion, blackmail, a scam, or a phishing attempt.</li>
</ul>
<h2>4. Respect other people&#39;s rights</h2>
<p>You may not record or submit content that infringes anyone&#39;s intellectual property or other rights, including copyrighted song lyrics, published text, speeches, scripts, audiobook or film dialogue, or trademarked material. Read the prompts in your own words.</p>
<h2>5. Do not misuse the Service</h2>
<p>You may not:</p>
<ul>
<li>Break, probe, or circumvent security, authentication, rate limits, or usage caps.</li>
<li>Access another user&#39;s account or content.</li>
<li>Scrape, crawl, reverse engineer, or automate access to the Service.</li>
<li>Resell, sublicense, or provide the Service to third parties as a voice-cloning service.</li>
<li>Use the Service to build a competing product or to train any machine learning model.</li>
<li>Upload malware, or use the Service to distribute spam or unsolicited messages.</li>
</ul>
<h2>6. Do not use ESSENCE for things it is not</h2>
<p>ESSENCE is a private voice keepsake vault. It is not a will, a trust, an estate service, a medical or legal record, a crisis service, or a delivery service. <strong>Nothing you store in ESSENCE is sent to anyone, and nothing you store in it has legal effect.</strong> Do not use it as the only place you keep instructions, credentials, or information that someone will need to find.</p>
<h2>7. Reporting a violation</h2>
<p>If you believe someone has used ESSENCE to impersonate you, clone your voice without permission, or otherwise violate this policy, email <strong><a href="mailto:help@essencevault.app">help@essencevault.app</a></strong> with:</p>
<ul>
<li>What happened, and any audio, links, or screenshots you have.</li>
<li>The identity of the person or account, if you know it.</li>
<li>Your contact information so we can follow up.</li>
</ul>
<p><strong>If you believe your voice has been cloned without your consent, say so in the subject line and we will prioritize it.</strong> We aim to acknowledge reports within <strong>3 business days</strong>.</p>
<p>Because all content in ESSENCE is private to its creator and nothing is delivered or published, we may not be able to independently locate content described in a report. We will do what we reasonably can, including suspending an account while we look into it.</p>
<h2>8. What we do about violations</h2>
<p>Depending on what happened, we may: contact you for an explanation, remove content, disable a voice model, restrict features, suspend the account, terminate the account permanently, or report the matter to law enforcement or affected parties.</p>
<p><strong>We may act without prior notice where we believe there is a risk to a person&#39;s safety, a legal obligation, or a risk to the Service.</strong> We are not obligated to monitor content, and we do not screen it proactively. Enforcement is manual and complaint-driven.</p>
<p>Where we can do so, we will tell you what happened and why, and give you a way to respond at <a href="mailto:help@essencevault.app">help@essencevault.app</a>.</p>
<h2>9. Changes</h2>
<p>We may update this policy. Material changes will be notified as described in the Terms of Service.</p>`,
  },
  "beta-terms": {
    slug: "beta-terms",
    navLabel: "Beta Terms",
    title: "ESSENCE Beta Participation Terms",
    effectiveLabel: "September 1, 2026",
    html: `<h2>1. What this is</h2>
<p>ESSENCE is operated by ESSENCE APP LLC, a Florida limited liability company (&quot;ESSENCE,&quot; &quot;we,&quot; &quot;us&quot;).</p>
<p>You have been invited to test a <strong>pre-release version</strong> of ESSENCE (the &quot;Beta&quot;). These Beta Participation Terms apply in addition to the <a href="/terms">Terms of Service</a>, the <a href="/privacy">Privacy Policy</a>, and the <a href="/acceptable-use">Acceptable Use Policy</a>. <strong>Where this document conflicts with the Terms of Service, this document wins for the duration of the Beta.</strong></p>
<p>By accepting these terms and using the Beta, you agree to them. Participation is voluntary and you can stop at any time.</p>
<h2>2. The Beta is unfinished software</h2>
<p>Please take this section literally.</p>
<ul>
<li><strong>The Beta may lose your data.</strong> Recordings, voice models, and messages may be deleted, corrupted, or become unplayable, by accident or as part of a planned reset. <strong>We may need to wipe all Beta data before launch.</strong></li>
<li><strong>The Beta may break, be unavailable, or behave incorrectly</strong>, without notice.</li>
<li><strong>Features may change or be removed</strong>, including features you rely on.</li>
<li><strong>We do not back up your audio.</strong> Our infrastructure&#39;s backups cover database records only. If a recording is lost, we may not be able to restore it.</li>
</ul>
<p><strong>Do not record anything into the Beta that you could not bear to lose, and do not treat the Beta as the only copy of anything meaningful to you.</strong> If a recording matters, keep your own copy on your own device.</p>
<h2>3. There is no delivery, and no posthumous release</h2>
<p>This bears repeating in a document about legacy voice messages, because the concept invites an assumption that is not true:</p>
<p><strong>ESSENCE does not send your messages to anyone, ever.</strong> There is no email or text delivery, no scheduling, no death or incapacity verification, and no release trigger. The people you name in the app are private labels in your own vault. <strong>We do not have their contact information and we will never contact them.</strong> Only you can play back your messages, from inside your own account.</p>
<p>Do not participate in the Beta on the understanding that anything will reach anyone.</p>
<h2>4. Your voice, and your consent</h2>
<p>The Beta creates a synthetic model of your voice from recordings you make. That is sensitive, and it is optional.</p>
<ul>
<li><strong>You must affirmatively consent before any voice model is created.</strong> Nothing is created without it.</li>
<li><strong>You may only record your own voice.</strong> Not a family member&#39;s, not anyone else&#39;s, living or deceased. See the Acceptable Use Policy.</li>
<li><strong>We do not use your recordings to train AI models.</strong> We turned off model training on our voice provider account before the Beta opened.</li>
<li><strong>You can withdraw at any time</strong> by deleting your account, which removes your content from our systems and instructs our voice provider to delete the voice model.</li>
</ul>
<p>The Privacy Policy describes exactly what we collect, who processes it, how long it lasts, and what deletion does and does not reach. Please read it before your first recording rather than after.</p>
<h2>5. Cost</h2>
<p><strong>The Beta is free.</strong> You will not be charged, and no payment method is required during the Beta.</p>
<p>We may end the Beta and move to a paid product. <strong>If we do, we will tell you before anything becomes paid, and we will never convert you to a paid subscription automatically.</strong> You would have to sign up deliberately.</p>
<h2>6. Feedback</h2>
<p>We would like your feedback, and you are under no obligation to give any.</p>
<p>If you do give us feedback, ideas, bug reports, or suggestions, <strong>you grant us a perpetual, irrevocable, worldwide, royalty-free right to use them for any purpose, including building them into the product, without payment, credit, or obligation to you.</strong> Feedback is not confidential and does not create any ownership interest for you in ESSENCE. This does not affect your ownership of your own recordings and messages, which remains yours under the Terms of Service.</p>
<h2>7. Confidentiality</h2>
<p>The Beta is not public. Please do not publish screenshots, recordings, screen captures, or descriptions of unreleased features publicly, and please do not share your access with anyone else. You can of course talk about your experience privately, and you can tell us anything.</p>
<p>This obligation ends when the relevant feature becomes publicly available.</p>
<h2>8. No warranties, and limited liability</h2>
<p><strong>THE BETA IS PROVIDED &quot;AS IS,&quot; WITH ALL FAULTS, AND WITHOUT WARRANTY OF ANY KIND.</strong> We disclaim all express and implied warranties to the fullest extent permitted by law, including any warranty of merchantability, fitness for a particular purpose, reliability, availability, accuracy, or data preservation.</p>
<p>Without limiting the disclaimers in the Terms of Service, we specifically disclaim liability for <strong>loss, corruption, or deletion of your recordings, voice model, or messages during or after the Beta</strong>, and for <strong>emotional distress arising from the loss of, absence of, or content of any recording or message.</strong></p>
<p>The limitation of liability in the Terms of Service applies. Because the Beta is free, our total liability to you for anything arising from the Beta is limited to <strong>US$100</strong>.</p>
<h2>9. Ending the Beta</h2>
<p>We may end the Beta, remove any participant, or change these terms at any time, with or without notice.</p>
<p><strong>Before we shut the Beta down or wipe Beta data, we will make reasonable efforts to give you at least 14 days&#39; notice by email</strong>, so that you can save anything you want to keep. If self-serve export does not exist yet, email <strong><a href="mailto:help@essencevault.app">help@essencevault.app</a></strong> and we will get your recordings and messages to you manually.</p>
<p>You may leave at any time by deleting your account in Settings.</p>
<h2>10. Support and contact</h2>
<p>The Beta is supported by email at <strong><a href="mailto:help@essencevault.app">help@essencevault.app</a></strong>. We are a very small team, so please be patient with response times. Bug reports are welcome and genuinely useful.</p>
<p><strong>ESSENCE APP LLC</strong>, 610 W Las Olas Blvd, #513, Fort Lauderdale, FL 33312</p>`,
  },
};
