#!/usr/bin/env node
// Follow-ups index generator + drift check.
//
//   node scripts/followups.mjs --build   regenerate docs/follow-ups/INDEX.md
//   node scripts/followups.mjs --check    fail (exit 1) if INDEX.md is stale
//
// One file per follow-up lives in docs/follow-ups/<YYYY-MM-DD>-<slug>.md with
// YAML front-matter (see docs/follow-ups/README.md). The date-slug id means
// concurrent triage never collides on a shared counter — the whole point of
// the per-file layout (FOLLOW_UPS.md § "Active follow-ups moved").
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const DIR = 'docs/follow-ups';
const INDEX = join(DIR, 'INDEX.md');
const BANNER = '<!-- GENERATED by scripts/followups.mjs — DO NOT EDIT. Run `npm run followups:build`. -->';
const PRIORITY_ORDER = { P1: 1, P2: 2, P3: 3, P4: 4 };
const STATUS_GROUPS = [
  ['open', 'Open'],
  ['decision', 'Decision (owner call)'],
  ['resolved', 'Resolved'],
  ['dropped', 'Dropped'],
];

function parseFrontMatter(text, file) {
  const m = text.match(/^---\n([\s\S]*?)\n---/);
  if (!m) throw new Error(`${file}: missing front-matter`);
  const fm = {};
  for (const line of m[1].split('\n')) {
    const kv = line.match(/^([a-z_]+):\s?(.*)$/);
    if (!kv) continue;
    let v = kv[2].trim();
    if (v.startsWith('"')) { try { v = JSON.parse(v); } catch { /* keep raw */ } }
    fm[kv[1]] = v === '' ? null : v;
  }
  return fm;
}

function loadItems() {
  const files = readdirSync(DIR).filter(
    (f) => f.endsWith('.md') && f !== 'INDEX.md' && f !== 'README.md'
  );
  const items = files.map((f) => {
    const fm = parseFrontMatter(readFileSync(join(DIR, f), 'utf8'), f);
    for (const req of ['id', 'priority', 'status', 'opened', 'summary']) {
      if (!fm[req]) throw new Error(`${f}: front-matter missing required "${req}"`);
    }
    if (!STATUS_GROUPS.some(([s]) => s === fm.status))
      throw new Error(`${f}: unknown status "${fm.status}"`);
    return { file: f, ...fm };
  });
  // deterministic order: priority, then opened date, then id
  items.sort(
    (a, b) =>
      (PRIORITY_ORDER[a.priority] || 9) - (PRIORITY_ORDER[b.priority] || 9) ||
      String(a.opened).localeCompare(String(b.opened)) ||
      a.id.localeCompare(b.id)
  );
  return items;
}

function render(items) {
  const esc = (s) => String(s).replace(/\|/g, '\\|');
  const out = [
    BANNER,
    '',
    '# Follow-ups index',
    '',
    `One row per item in \`docs/follow-ups/\`. **Generated — do not hand-edit.** Add a follow-up by creating a new \`<YYYY-MM-DD>-<slug>.md\` file (see [README](./README.md)), then run \`npm run followups:build\`.`,
    '',
    `Total: ${items.length} · ` +
      STATUS_GROUPS.map(([s, label]) => `${items.filter((i) => i.status === s).length} ${label.toLowerCase().replace(/ .*/, '')}`).join(' · '),
    '',
  ];
  for (const [status, label] of STATUS_GROUPS) {
    const group = items.filter((i) => i.status === status);
    if (!group.length) continue;
    out.push(`## ${label} (${group.length})`, '');
    out.push('| P | Summary | Opened | Legacy | File |', '|---|---------|--------|--------|------|');
    for (const i of group) {
      const legacy = i.legacy_id ? `FU-${i.legacy_id}` : '—';
      out.push(`| ${i.priority} | ${esc(i.summary)} | ${i.opened} | ${legacy} | [\`${i.file}\`](./${i.file}) |`);
    }
    out.push('');
  }
  return out.join('\n').replace(/\s+$/, '') + '\n';
}

const mode = process.argv[2];
const rendered = render(loadItems());
if (mode === '--build') {
  writeFileSync(INDEX, rendered);
  console.log(`followups: wrote ${INDEX}`);
} else if (mode === '--check') {
  let current = '';
  try { current = readFileSync(INDEX, 'utf8'); } catch { /* missing */ }
  if (current !== rendered) {
    console.error('followups: INDEX.md is stale. Run `npm run followups:build` and commit.');
    process.exit(1);
  }
  console.log('followups: INDEX.md is up to date.');
} else {
  console.error('usage: node scripts/followups.mjs --build|--check');
  process.exit(2);
}
