#!/usr/bin/env node
// Public legal-page content generator + drift check.
//
//   node scripts/legal-build.mjs --build   regenerate src/content/legal/generated.ts
//   node scripts/legal-build.mjs --check    fail (exit 1) if the generated file is stale
//
// Single source of truth is the reviewed markdown in docs/legal/. Each public
// document is sliced to its PUBLISHABLE BODY (the header block and the trailing
// "Open items"/"Implementation notes" section are internal-only and dropped),
// inline `[Owner: …]` / `[INSERT …]` notes are stripped, and the result is
// converted to HTML with marked (GFM, so the policy tables render).
//
// SAFETY: after conversion the HTML is scanned for internal-only phrases. If any
// survive, the build THROWS rather than publish a leak onto a public legal page.
// This is deliberate — a leaked "[Owner note: …]" on a Terms page is exactly the
// failure this generator exists to prevent.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { marked } from 'marked';

const OUT = 'src/content/legal/generated.ts';
const BANNER =
  '// GENERATED by scripts/legal-build.mjs — DO NOT EDIT. Run `npm run legal:build`.';

// The four PUBLIC documents. The Compliance Pack and attorney packet are
// internal and deliberately absent.
const DOCS = [
  {
    slug: 'terms',
    navLabel: 'Terms',
    file: 'docs/legal/ESSENCE_Terms_of_Service_v1_DRAFT.md',
  },
  {
    slug: 'privacy',
    navLabel: 'Privacy',
    file: 'docs/legal/ESSENCE_Privacy_Policy_v1_DRAFT.md',
  },
  {
    slug: 'acceptable-use',
    navLabel: 'Acceptable Use',
    file: 'docs/legal/ESSENCE_Acceptable_Use_Policy_v1_DRAFT.md',
  },
  {
    slug: 'beta-terms',
    navLabel: 'Beta Terms',
    file: 'docs/legal/ESSENCE_Beta_Participation_Terms_v1_DRAFT.md',
  },
];

// Phrases that must NEVER appear on a public page. Case-insensitive.
const FORBIDDEN = [
  'internal note',
  'delete before publishing',
  'open items',
  'implementation notes',
  'not reviewed by counsel',
  'draft v1.0',
  '[insert',
  'owner note',
  '[owner',
  '[counsel',
];

function titleOf(text, file) {
  const m = text.match(/^#\s+(.+?)\s*$/m);
  if (!m) throw new Error(`${file}: no H1 title found`);
  return m[1].trim();
}

function effectiveLabelOf(text, file) {
  const m = text.match(/\*\*Effective date:\*\*\s*(.+?)\s*$/m);
  if (!m) throw new Error(`${file}: no "**Effective date:**" line found`);
  return m[1].trim();
}

function publishableBody(text, file) {
  const lines = text.split('\n');

  // Start: the line AFTER the first standalone `---` (the header/body divider).
  const firstHr = lines.findIndex((l) => l.trim() === '---');
  if (firstHr === -1) throw new Error(`${file}: no header divider (---) found`);
  let start = firstHr + 1;

  // End: the LAST "## Open items…" / "## Implementation notes…" heading. That
  // block, and any trailing `---` immediately above it, are internal-only.
  let end = lines.length;
  for (let i = lines.length - 1; i > start; i--) {
    if (/^##\s+(open items|implementation notes)/i.test(lines[i].trim())) {
      end = i;
      // swallow a separator + blank lines directly above the heading
      let j = end - 1;
      while (j > start && lines[j].trim() === '') j--;
      if (j > start && lines[j].trim() === '---') end = j;
      break;
    }
  }

  let body = lines.slice(start, end).join('\n');

  // Strip inline internal notes embedded in the body, e.g.
  //   *[Owner note: … ]*   *[Owner: verify … ]*   [INSERT …]
  body = body.replace(/\*?\[\s*(owner|owner note|counsel|internal|insert)[^\]]*\]\*?/gi, '');

  // Collapse any blank lines left behind by a stripped note-only paragraph.
  body = body.replace(/\n{3,}/g, '\n\n').trim();
  return body;
}

function build() {
  const entries = DOCS.map(({ slug, navLabel, file }) => {
    const text = readFileSync(file, 'utf8');
    const title = titleOf(text, file);
    const effectiveLabel = effectiveLabelOf(text, file);
    const md = publishableBody(text, file);
    const html = marked.parse(md, { gfm: true, async: false }).trim();

    const hay = html.toLowerCase();
    for (const phrase of FORBIDDEN) {
      if (hay.includes(phrase)) {
        throw new Error(
          `LEAK GUARD: "${phrase}" reached the public HTML for ${slug} (${file}). ` +
            `Refusing to publish internal content on a legal page.`,
        );
      }
    }
    return { slug, navLabel, title, effectiveLabel, html };
  });

  const esc = (s) =>
    s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

  const body = entries
    .map(
      (e) => `  ${JSON.stringify(e.slug)}: {
    slug: ${JSON.stringify(e.slug)},
    navLabel: ${JSON.stringify(e.navLabel)},
    title: ${JSON.stringify(e.title)},
    effectiveLabel: ${JSON.stringify(e.effectiveLabel)},
    html: \`${esc(e.html)}\`,
  },`,
    )
    .join('\n');

  return `${BANNER}

export interface LegalDocContent {
  /** URL slug and record key, e.g. "terms". */
  slug: string;
  /** Short cross-nav label, e.g. "Terms". */
  navLabel: string;
  /** Document title (the source H1), e.g. "ESSENCE Terms of Service". */
  title: string;
  /** Human effective-date label, e.g. "September 1, 2026". */
  effectiveLabel: string;
  /** Pre-rendered, leak-checked body HTML (from the reviewed markdown). */
  html: string;
}

/** Ordered slugs — drives cross-document footer nav. */
export const LEGAL_ORDER = [${DOCS.map((d) => JSON.stringify(d.slug)).join(', ')}] as const;

export const LEGAL_DOCS: Record<string, LegalDocContent> = {
${body}
};
`;
}

const mode = process.argv[2];
const generated = build();

if (mode === '--check') {
  let current = '';
  try {
    current = readFileSync(OUT, 'utf8');
  } catch {
    /* missing → stale */
  }
  if (current !== generated) {
    console.error(
      `legal:check — ${OUT} is stale. Run \`npm run legal:build\` and commit.`,
    );
    process.exit(1);
  }
  console.log(`legal:check — ${OUT} is up to date.`);
} else if (mode === '--build') {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, generated);
  console.log(`legal:build — wrote ${OUT} (${DOCS.length} documents).`);
} else {
  console.error('usage: legal-build.mjs --build | --check');
  process.exit(2);
}
